name: ci
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
    branches:
      - develop
      - master

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        run: |
          version=$(make showVersion)
          echo "version=$version" >> $GITHUB_ENV

      - name: Check version
        run: |
          check_result=$(docker manifest inspect ghcr.io/murilo-bracero/spellscan-card-loader:$version > /dev/null ; echo $?)
          if [[ "$check_result" == "0" ]]; then
            echo "Version $version already exists in ghcr.io"
            exit 1
          fi